name = "Don't Starve Debugger"
description = "This mod will process crash report and decide which mod is to blame."
author = "Nymphoenix"
version = "1.0.3"
client_only_mod = true
all_clients_require_mod = false
api_version = 10
dst_compatible = true
dont_starve_compatible = true
reign_of_giants_compatible = true
shipwrecked_compatible = true
restart_required = false
standalone = false
forumthread = ""
